using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudyFlow.Domain.Entities;

[Table("ai_requests")]
public partial class AiRequest
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("user_id")]
    public int UserId { get; set; }

    [Column("topic_id")]
    public int TopicId { get; set; }

    [Column("request_type")]
    [StringLength(100)]
    [Unicode(false)]
    public string RequestType { get; set; } = null!;

    /// <summary>
    /// Prompt sent to the AI model.
    /// </summary>
    [Column("input_prompt")]
    [Unicode(false)]
    public string InputPrompt { get; set; } = null!;

    /// <summary>
    /// Response generated by the AI.
    /// </summary>

    [Column("ai_response")]
    [Unicode(false)]
    public string? AiResponse { get; set; }

    /// <summary>
    /// Timestamp indicating when the topic was created.
    /// Stored in UTC to ensure consistency across time zones.
    /// </summary>
    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("TopicId")]
    [InverseProperty("AiRequests")]
    public virtual Topic Topic { get; set; } = null!;

    [ForeignKey("UserId")]
    [InverseProperty("AiRequests")]
    public virtual User User { get; set; } = null!;
}
